version: '3.8'
services:
  frontend:
    build:
      context: ./github-repo-analyzer
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./analyzer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
